DEVISE_JWT_SECRET_KEY: RANDOM_SECRET
HTTP_PORT: 4000
BASE_DATABASE_URL: postgres://genos:m3rashid@localhost:5432
DATABASE_URL: postgres://genos:m3rashid@localhost:5432/hms?sslmode=disable
DATABASE_TESTURL: postgres://genos:m3rashid@localhost:5432/hms_test?sslmode=disable
REDIS_URL: redis://localhost:6379/7
