DEVISE_JWT_SECRET_KEY: RANDOM_SECRET
HTTP_PORT: 3002
BASE_DATABASE_URL: postgres://genos:m3rashid@localhost:5432
DATABASE_URL: postgres://genos:m3rashid@localhost:5432/hms?sslmode=disable
DATABASE_TESTURL: postgres://genos:m3rashid@localhost:5432/hms_test?sslmode=disable
REDIS_URL: redis://localhost:6379/7
WORKERS: CollectIpWorker,QcloudSmsWorker
SMS_APPID:
SMS_APPKEY:
SMS_TEMPID:
SMS_APPLYTEMPID:
ALIPAY_APP_ID:
ALIPAY_PRIVATE_KEY:
ALIPAY_PUBLIC_KEY:
ALIPAY_URL:
INFLUXDB_DB: hms
INFLUXDB_HOST: localhost
INFLUXDB_PORT: '8086'
