-- Types for Profile
CREATE TYPE sex AS ENUM ('MALE','FEMALE','OTHERS');
CREATE TYPE role AS ENUM ('DOCTOR','ADMIN','RECEPTIONIST','PHARMACIST','INVENTORY_MGR','CO_ADMIN','OTHER','PATIENT');
CREATE TYPE maritalStatus as ENUM ('SINGLE','MARRIED','DIVORCED','WIDOWED');
